import React, { useState, useEffect, useMemo } from "react";
import {
  Search, SlidersHorizontal, Download, Bookmark, BookmarkCheck, MessageCircle,
  Trophy, LogOut, Upload, Trash2, Plus, Pencil, X, Check, FileText, Users,
  LayoutGrid, BarChart3, Send, Eye, EyeOff, Loader2, Clock, Medal, Sparkles,
  GraduationCap, ShieldCheck, BookOpen, Mail, Lock, Hash, ArrowLeft, RotateCcw,
  AlertCircle, ChevronDown
} from "lucide-react";
import {
  BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Cell
} from "recharts";

/* ------------------------------------------------------------------ */
/* Constants & helpers                                                 */
/* ------------------------------------------------------------------ */

const BRANCHES = ["CSE", "ECE", "ME", "CE", "EE"];
const SEMESTERS = ["1", "2", "3", "4", "5", "6", "7", "8"];
const CURRENT_YEAR = 2026;
const YEARS = Array.from({ length: 6 }, (_, i) => String(CURRENT_YEAR - i));

function uid() {
  return "id_" + Date.now().toString(36) + Math.random().toString(36).slice(2, 8);
}

function formatDate(iso) {
  try {
    return new Date(iso).toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" });
  } catch (e) {
    return "";
  }
}

function formatRelative(iso) {
  const diff = Date.now() - new Date(iso).getTime();
  const days = Math.floor(diff / 86400000);
  if (days <= 0) return "today";
  if (days === 1) return "yesterday";
  if (days < 30) return `${days}d ago`;
  const months = Math.floor(days / 30);
  if (months < 12) return `${months}mo ago`;
  return `${Math.floor(months / 12)}y ago`;
}

function generatePlaceholderPdf(title, meta) {
  const esc = (s) => String(s).replace(/[()\\]/g, " ").slice(0, 90);
  const t = esc(title);
  const m = esc(meta);
  const content =
    `BT /F1 16 Tf 72 700 Td (${t}) Tj ET\n` +
    `BT /F2 10 Tf 72 678 Td (${m}) Tj ET\n` +
    `BT /F2 9 Tf 72 648 Td (Demo placeholder generated by ExamVault. No original file was uploaded for this entry.) Tj ET`;
  const pdf =
    `%PDF-1.4\n` +
    `1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj\n` +
    `2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj\n` +
    `3 0 obj<</Type/Page/Parent 2 0 R/Resources<</Font<</F1 4 0 R/F2 5 0 R>>>>/MediaBox[0 0 612 792]/Contents 6 0 R>>endobj\n` +
    `4 0 obj<</Type/Font/Subtype/Type1/BaseFont/Helvetica-Bold>>endobj\n` +
    `5 0 obj<</Type/Font/Subtype/Type1/BaseFont/Helvetica>>endobj\n` +
    `6 0 obj<</Length ${content.length}>>\nstream\n${content}\nendstream\nendobj\n` +
    `trailer<</Size 7/Root 1 0 R>>\n%%EOF`;
  return new Blob([pdf], { type: "application/pdf" });
}

function buildSeed() {
  const now = Date.now();
  const iso = (daysAgo) => new Date(now - daysAgo * 86400000).toISOString();
  const users = {
    admin01: { id: "admin01", role: "admin", name: "Administrator", password: "admin123" },
    stu_aarav: { id: "stu_aarav", role: "student", name: "Aarav Sharma", enrollmentId: "CSE21B045", email: "aarav.sharma@clg.edu", branch: "CSE", semester: "5", password: "student123", points: 24, joinedAt: iso(120) },
    stu_priya: { id: "stu_priya", role: "student", name: "Priya Patel", enrollmentId: "ECE21B012", email: "priya.patel@clg.edu", branch: "ECE", semester: "5", password: "student123", points: 31, joinedAt: iso(110) },
    stu_rohan: { id: "stu_rohan", role: "student", name: "Rohan Verma", enrollmentId: "CSE22B078", email: "rohan.verma@clg.edu", branch: "CSE", semester: "3", password: "student123", points: 9, joinedAt: iso(60) },
    stu_sneha: { id: "stu_sneha", role: "student", name: "Sneha Iyer", enrollmentId: "ME21B021", email: "sneha.iyer@clg.edu", branch: "ME", semester: "5", password: "student123", points: 17, joinedAt: iso(90) }
  };
  const papers = {
    p1: { id: "p1", title: "Data Structures & Algorithms", subject: "DSA", year: "2025", semester: "3", branch: "CSE", description: "End-semester examination covering trees, graphs, and sorting algorithms.", fileName: null, hasFile: false, downloads: 41, uploadedBy: "admin01", uploadedAt: iso(40) },
    p2: { id: "p2", title: "Database Management Systems", subject: "DBMS", year: "2025", semester: "4", branch: "CSE", description: "Covers normalization, SQL queries, and transaction management.", fileName: null, hasFile: false, downloads: 36, uploadedBy: "admin01", uploadedAt: iso(38) },
    p3: { id: "p3", title: "Digital Electronics", subject: "Digital Electronics", year: "2024", semester: "3", branch: "ECE", description: "Combinational and sequential circuits, K-maps.", fileName: null, hasFile: false, downloads: 22, uploadedBy: "admin01", uploadedAt: iso(70) },
    p4: { id: "p4", title: "Computer Networks", subject: "Networks", year: "2025", semester: "5", branch: "CSE", description: "OSI model, routing protocols, and network security basics.", fileName: null, hasFile: false, downloads: 29, uploadedBy: "admin01", uploadedAt: iso(20) },
    p5: { id: "p5", title: "Engineering Thermodynamics", subject: "Thermodynamics", year: "2024", semester: "4", branch: "ME", description: "Laws of thermodynamics, entropy, and cycles.", fileName: null, hasFile: false, downloads: 14, uploadedBy: "admin01", uploadedAt: iso(80) },
    p6: { id: "p6", title: "Signals & Systems", subject: "Signals & Systems", year: "2024", semester: "4", branch: "ECE", description: "Fourier transforms, LTI systems, and convolution.", fileName: null, hasFile: false, downloads: 18, uploadedBy: "admin01", uploadedAt: iso(55) },
    p7: { id: "p7", title: "Operating Systems", subject: "Operating Systems", year: "2025", semester: "5", branch: "CSE", description: "Process scheduling, memory management, and deadlocks.", fileName: null, hasFile: false, downloads: 33, uploadedBy: "admin01", uploadedAt: iso(15) },
    p8: { id: "p8", title: "Engineering Mathematics III", subject: "Mathematics", year: "2024", semester: "3", branch: "CSE", description: "Laplace transforms, complex analysis, and numerical methods.", fileName: null, hasFile: false, downloads: 27, uploadedBy: "admin01", uploadedAt: iso(95) }
  };
  const bookmarks = { stu_aarav: ["p1", "p4"], stu_priya: ["p3", "p6"] };
  const downloads = {
    stu_aarav: [{ paperId: "p1", ts: iso(2) }, { paperId: "p7", ts: iso(5) }],
    stu_priya: [{ paperId: "p3", ts: iso(1) }, { paperId: "p6", ts: iso(3) }]
  };
  const comments = {
    p1: [{ id: "c1", studentId: "stu_priya", name: "Priya Patel", text: "Q4 on AVL rotations is almost identical to the 2023 paper — good one to practice.", ts: iso(3) }],
    p7: [{ id: "c2", studentId: "stu_aarav", name: "Aarav Sharma", text: "The Banker's algorithm question repeats nearly every year, don't skip it.", ts: iso(4) }]
  };
  return { users, papers, bookmarks, downloads, comments };
}

/* ------------------------------------------------------------------ */
/* Small shared UI pieces                                              */
/* ------------------------------------------------------------------ */

const Seal = ({ children, size = 42, rotate = 0, tone = "amber" }) => (
  <div className={`ev-seal ev-tone-${tone}`} style={{ width: size, height: size, transform: `rotate(${rotate}deg)` }}>
    <span>{children}</span>
  </div>
);

const Logo = ({ size = 38 }) => (
  <div className="ev-logo" style={{ width: size, height: size }}>
    <div className="ev-logo-ring">
      <BookOpen size={size * 0.45} strokeWidth={2.2} />
    </div>
  </div>
);

const Toasts = ({ toasts }) => (
  <div className="ev-toast-wrap">
    {toasts.map((t) => (
      <div key={t.id} className={`ev-toast ev-toast-${t.type}`}>
        {t.type === "error" ? <AlertCircle size={16} /> : <Check size={16} />}
        <span>{t.msg}</span>
      </div>
    ))}
  </div>
);

const Modal = ({ title, onClose, children, wide }) => (
  <div className="ev-modal-overlay" onClick={onClose}>
    <div className={`ev-modal ${wide ? "ev-modal-wide" : ""}`} onClick={(e) => e.stopPropagation()}>
      <div className="ev-modal-head">
        <h3>{title}</h3>
        <button className="ev-icon-btn" onClick={onClose}><X size={18} /></button>
      </div>
      <div className="ev-modal-body">{children}</div>
    </div>
  </div>
);

const Field = ({ label, icon, children }) => (
  <label className="ev-field">
    <span className="ev-field-label">{icon}{label}</span>
    {children}
  </label>
);

const EmptyState = ({ icon, title, body }) => (
  <div className="ev-empty">
    {icon}
    <h4>{title}</h4>
    <p>{body}</p>
  </div>
);

/* ------------------------------------------------------------------ */
/* Landing                                                             */
/* ------------------------------------------------------------------ */

const Landing = ({ onPickStudent, onPickAdmin }) => (
  <div className="ev-landing">
    <div className="ev-landing-inner">
      <div className="ev-brandmark">
        <Logo size={56} />
        <div>
          <div className="ev-eyebrow">Madhav Institute of Technology & Science</div>
          <h1>ExamVault Portal</h1>
          <div className="ev-separator"></div>
        </div>
      </div>
      <p className="ev-landing-sub">
        The official academic archive for previous-year question papers. 
        Access verified institutional resources, monitor your download history, and review peer preparation benchmarks.
      </p>
      
      <div className="ev-landing-cards">
        <button className="ev-portal-card" onClick={onPickStudent}>
          <div className="ev-portal-card-left">
            <Seal rotate={0} size={44} tone="amber">STU</Seal>
            <div>
              <h3>Student Gateway</h3>
              <p>Browse reference papers, track bookmarks, and access discussion threads.</p>
            </div>
          </div>
          <ArrowLeft size={18} className="ev-portal-arrow" />
        </button>
        
        <button className="ev-portal-card ev-portal-card-admin" onClick={onPickAdmin}>
          <div className="ev-portal-card-left">
            <Seal rotate={0} size={44} tone="coral">ADM</Seal>
            <div>
              <h3>Faculty & Admin Console</h3>
              <p>Publish examination papers, curate the archive data, and manage rosters.</p>
            </div>
          </div>
          <ArrowLeft size={18} className="ev-portal-arrow" />
        </button>
      </div>
      
      <div className="ev-landing-foot">
        <span>Institutional Demo Access Key:</span>
        <code>Student: CSE21B045 / student123</code>
        <code>Admin: admin01 / admin123</code>
      </div>
    </div>
  </div>
);

/* ------------------------------------------------------------------ */
/* Auth screens                                                        */
/* ------------------------------------------------------------------ */

const AuthShell = ({ tone, sealLabel, title, subtitle, onBack, children }) => (
  <div className="ev-auth">
    <div className={`ev-auth-brand ev-tone-bg-${tone}`}>
      <button className="ev-back-link" onClick={onBack}><ArrowLeft size={16} /> Return to Home</button>
      <div className="ev-auth-brand-mid">
        <Logo size={64} />
        <h2>{title}</h2>
        <div className="ev-auth-line"></div>
        <p>{subtitle}</p>
      </div>
      <div className="ev-auth-brand-foot">Madhav Institute of Technology & Science © 2026</div>
    </div>
    <div className="ev-auth-form-side">
      <div className="ev-auth-form-container">
        {children}
      </div>
    </div>
  </div>
);

const StudentAuth = ({ mode, setMode, onLogin, onRegister, onBack }) => {
  const [identifier, setIdentifier] = useState("");
  const [password, setPassword] = useState("");
  const [showPw, setShowPw] = useState(false);

  const [rName, setRName] = useState("");
  const [rEnroll, setREnroll] = useState("");
  const [rEmail, setREmail] = useState("");
  const [rBranch, setRBranch] = useState(BRANCHES[0]);
  const [rSem, setRSem] = useState(SEMESTERS[0]);
  const [rPass, setRPass] = useState("");
  const [rPass2, setRPass2] = useState("");

  return (
    <AuthShell
      tone="amber"
      sealLabel="STU"
      title="Student Information System"
      subtitle="Authenticate using your university deployment credentials or assigned college email."
      onBack={onBack}
    >
      <div className="ev-auth-tabs">
        <button className={mode === "login" ? "active" : ""} onClick={() => setMode("login")}>Sign In</button>
        <button className={mode === "register" ? "active" : ""} onClick={() => setMode("register")}>Enroll Account</button>
      </div>

      {mode === "login" ? (
        <form
          className="ev-form"
          onSubmit={(e) => { e.preventDefault(); onLogin(identifier, password); }}
        >
          <Field label="Enrollment ID / Institutional Email" icon={<Hash size={13} />}>
            <input className="ev-input" placeholder="e.g., 0901CS211XXX or name@mitsgwalior.in" value={identifier} onChange={(e) => setIdentifier(e.target.value)} required />
          </Field>
          <Field label="Account Password" icon={<Lock size={13} />}>
            <div className="ev-pw-wrap">
              <input className="ev-input" type={showPw ? "text" : "password"} placeholder="••••••••" value={password} onChange={(e) => setPassword(e.target.value)} required />
              <button type="button" className="ev-pw-toggle" onClick={() => setShowPw((s) => !s)}>
                {showPw ? <EyeOff size={15} /> : <Eye size={15} />}
              </button>
            </div>
          </Field>
          <button className="ev-btn ev-btn-primary ev-btn-block" type="submit">Verify & Enter Portal</button>
        </form>
      ) : (
        <form
          className="ev-form"
          onSubmit={(e) => {
            e.preventDefault();
            onRegister({ name: rName, enrollmentId: rEnroll, email: rEmail, branch: rBranch, semester: rSem, password: rPass, confirm: rPass2 });
          }}
        >
          <Field label="Full Legal Name"><input className="ev-input" placeholder="John Doe" value={rName} onChange={(e) => setRName(e.target.value)} required /></Field>
          <div className="ev-form-row">
            <Field label="Enrollment ID"><input className="ev-input" placeholder="0901CS..." value={rEnroll} onChange={(e) => setREnroll(e.target.value)} required /></Field>
            <Field label="College Email"><input className="ev-input" type="email" placeholder="name@clg.edu" value={rEmail} onChange={(e) => setREmail(e.target.value)} required /></Field>
          </div>
          <div className="ev-form-row">
            <Field label="Academic Department">
              <select className="ev-input" value={rBranch} onChange={(e) => setRBranch(e.target.value)}>
                {BRANCHES.map((b) => <option key={b} value={b}>{b}</option>)}
              </select>
            </Field>
            <Field label="Current Semester">
              <select className="ev-input" value={rSem} onChange={(e) => setRSem(e.target.value)}>
                {SEMESTERS.map((s) => <option key={s} value={s}>Semester {s}</option>)}
              </select>
            </Field>
          </div>
          <div className="ev-form-row">
            <Field label="Password"><input className="ev-input" type="password" value={rPass} onChange={(e) => setRPass(e.target.value)} required /></Field>
            <Field label="Confirm Password"><input className="ev-input" type="password" value={rPass2} onChange={(e) => setRPass2(e.target.value)} required /></Field>
          </div>
          <button className="ev-btn ev-btn-primary ev-btn-block" type="submit">Complete Registration</button>
        </form>
      )}
    </AuthShell>
  );
};

const AdminAuth = ({ onLogin, onBack }) => {
  const [id, setId] = useState("");
  const [password, setPassword] = useState("");
  return (
    <AuthShell tone="coral" sealLabel="ADM" title="Faculty & Controller Terminal" subtitle="Authorized personnel access node. System actions are cryptographically logged." onBack={onBack}>
      <form className="ev-form" onSubmit={(e) => { e.preventDefault(); onLogin(id, password); }}>
        <Field label="Faculty Identity Code" icon={<ShieldCheck size={13} />}>
          <input className="ev-input" placeholder="admin01" value={id} onChange={(e) => setId(e.target.value)} required />
        </Field>
        <Field label="Terminal Access Password" icon={<Lock size={13} />}>
          <input className="ev-input" type="password" placeholder="••••••••" value={password} onChange={(e) => setPassword(e.target.value)} required />
        </Field>
        <button className="ev-btn ev-btn-coral ev-btn-block" type="submit">Authenticate Clearance</button>
      </form>
    </AuthShell>
  );
};

/* ------------------------------------------------------------------ */
/* Paper card + comments                                               */
/* ------------------------------------------------------------------ */

const CommentsThread = ({ paperId, list, onAdd, currentUser }) => {
  const [text, setText] = useState("");
  return (
    <div className="ev-comments">
      {list.length === 0 && <p className="ev-comments-empty">No discussion yet — be the first to leave a tip for this paper.</p>}
      {list.map((c) => (
        <div key={c.id} className="ev-comment">
          <div className="ev-comment-avatar">{c.name.split(" ").map((p) => p[0]).join("").slice(0, 2)}</div>
          <div>
            <div className="ev-comment-meta"><strong>{c.name}</strong><span>{formatRelative(c.ts)}</span></div>
            <p>{c.text}</p>
          </div>
        </div>
      ))}
      {currentUser?.role === "student" && (
        <form
          className="ev-comment-form"
          onSubmit={(e) => { e.preventDefault(); if (!text.trim()) return; onAdd(paperId, text); setText(""); }}
        >
          <input className="ev-input" placeholder="Share a tip about this paper…" value={text} onChange={(e) => setText(e.target.value)} />
          <button className="ev-icon-btn ev-icon-btn-primary" type="submit"><Send size={15} /></button>
        </form>
      )}
    </div>
  );
};

const PaperCard = ({ paper, role, isBookmarked, onToggleBookmark, onDownload, commentList, onAddComment, currentUser, expanded, onToggleExpand, adminActions }) => (
  <div className="ev-paper-card">
    <div className="ev-paper-card-top">
      <div className="ev-paper-tags">
        <span className="ev-tag ev-tag-subject">{paper.subject}</span>
        <span className="ev-tag">{paper.year}</span>
        <span className="ev-tag">Sem {paper.semester}</span>
      </div>
      <Seal size={38} rotate={-7}>{paper.branch}</Seal>
    </div>
    <h4 className="ev-paper-title">{paper.title}</h4>
    {paper.description && <p className="ev-paper-desc">{paper.description}</p>}
    <div className="ev-paper-meta-row">
      <span><Clock size={12} /> {formatRelative(paper.uploadedAt)}</span>
      <span><Download size={12} /> {paper.downloads || 0} downloads</span>
    </div>

    <div className="ev-perf">
      {role === "student" ? (
        <div className="ev-paper-actions">
          <button className="ev-btn ev-btn-primary ev-btn-sm" onClick={() => onDownload(paper)}><Download size={14} /> Download</button>
          <button className={`ev-btn ev-btn-ghost ev-btn-sm ${isBookmarked ? "ev-bookmarked" : ""}`} onClick={() => onToggleBookmark(paper.id)}>
            {isBookmarked ? <BookmarkCheck size={14} /> : <Bookmark size={14} />} {isBookmarked ? "Saved" : "Save"}
          </button>
          <button className="ev-btn ev-btn-ghost ev-btn-sm" onClick={() => onToggleExpand(paper.id)}>
            <MessageCircle size={14} /> {commentList.length || ""} Discuss
          </button>
        </div>
      ) : (
        <div className="ev-paper-actions">
          <button className="ev-btn ev-btn-ghost ev-btn-sm" onClick={() => adminActions.onEdit(paper)}><Pencil size={14} /> Edit</button>
          <button className="ev-btn ev-btn-danger-ghost ev-btn-sm" onClick={() => adminActions.onDelete(paper.id)}><Trash2 size={14} /> Delete</button>
          <span className="ev-paper-filename">{paper.hasFile ? paper.fileName : "no file attached — demo PDF on download"}</span>
        </div>
      )}
    </div>

    {expanded && role === "student" && (
      <CommentsThread paperId={paper.id} list={commentList} onAdd={onAddComment} currentUser={currentUser} />
    )}
  </div>
);

/* ------------------------------------------------------------------ */
/* Leaderboard                                                         */
/* ------------------------------------------------------------------ */

const LeaderboardView = ({ students, currentUserId }) => {
  const ranked = useMemo(() => [...students].sort((a, b) => (b.points || 0) - (a.points || 0)), [students]);
  const chartData = ranked.slice(0, 6).map((s) => ({ name: s.name.split(" ")[0], points: s.points || 0, id: s.id }));
  const medalTone = (i) => (i === 0 ? "#F2A93B" : i === 1 ? "#9AA5B5" : i === 2 ? "#C2784A" : "#D7DCE5");

  return (
    <div className="ev-leaderboard">
      <div className="ev-card ev-chart-card">
        <h3><BarChart3 size={16} /> Top contributors</h3>
        <div style={{ width: "100%", height: 220 }}>
          <ResponsiveContainer>
            <BarChart data={chartData} margin={{ top: 8, right: 8, left: -16, bottom: 0 }}>
              <CartesianGrid strokeDasharray="3 3" stroke="#E3E7EF" vertical={false} />
              <XAxis dataKey="name" tick={{ fontSize: 11, fill: "#6B7686" }} axisLine={{ stroke: "#E3E7EF" }} tickLine={false} />
              <YAxis tick={{ fontSize: 11, fill: "#6B7686" }} axisLine={false} tickLine={false} width={28} />
              <Tooltip contentStyle={{ borderRadius: 10, border: "1px solid #E3E7EF", fontSize: 12 }} />
              <Bar dataKey="points" radius={[6, 6, 0, 0]}>
                {chartData.map((d, i) => (
                  <Cell key={d.id} fill={d.id === currentUserId ? "#2F9C8F" : "#F2A93B"} />
                ))}
              </Bar>
            </BarChart>
          </ResponsiveContainer>
        </div>
      </div>

      <div className="ev-card">
        <h3><Trophy size={16} /> Rankings</h3>
        <div className="ev-rank-list">
          {ranked.map((s, i) => (
            <div key={s.id} className={`ev-rank-row ${s.id === currentUserId ? "ev-rank-me" : ""}`}>
              <div className="ev-rank-pos">
                {i < 3 ? <Medal size={18} color={medalTone(i)} /> : <span>{i + 1}</span>}
              </div>
              <div className="ev-rank-name">
                <strong>{s.name}{s.id === currentUserId ? " (you)" : ""}</strong>
                <span>{s.branch} • Sem {s.semester}</span>
              </div>
              <div className="ev-rank-points">{s.points || 0} pts</div>
            </div>
          ))}
          {ranked.length === 0 && <EmptyState icon={<Trophy size={28} />} title="No students yet" body="The leaderboard will fill up as students join and stay active." />}
        </div>
      </div>
    </div>
  );
};

/* ------------------------------------------------------------------ */
/* Filter bar                                                          */
/* ------------------------------------------------------------------ */

const FilterBar = ({ filters, setFilters, subjects, branches }) => (
  <div className="ev-filterbar">
    <div className="ev-search-box">
      <Search size={16} />
      <input placeholder="Search by title or subject…" value={filters.q} onChange={(e) => setFilters((f) => ({ ...f, q: e.target.value }))} />
    </div>
    <select className="ev-input ev-filter-select" value={filters.subject} onChange={(e) => setFilters((f) => ({ ...f, subject: e.target.value }))}>
      <option value="">All subjects</option>
      {subjects.map((s) => <option key={s} value={s}>{s}</option>)}
    </select>
    <select className="ev-input ev-filter-select" value={filters.branch} onChange={(e) => setFilters((f) => ({ ...f, branch: e.target.value }))}>
      <option value="">All branches</option>
      {branches.map((b) => <option key={b} value={b}>{b}</option>)}
    </select>
    <select className="ev-input ev-filter-select" value={filters.semester} onChange={(e) => setFilters((f) => ({ ...f, semester: e.target.value }))}>
      <option value="">All semesters</option>
      {SEMESTERS.map((s) => <option key={s} value={s}>Sem {s}</option>)}
    </select>
    <select className="ev-input ev-filter-select" value={filters.year} onChange={(e) => setFilters((f) => ({ ...f, year: e.target.value }))}>
      <option value="">All years</option>
      {YEARS.map((y) => <option key={y} value={y}>{y}</option>)}
    </select>
    {(filters.q || filters.subject || filters.branch || filters.semester || filters.year) && (
      <button className="ev-btn ev-btn-ghost ev-btn-sm" onClick={() => setFilters({ q: "", subject: "", branch: "", semester: "", year: "" })}>
        <RotateCcw size={13} /> Clear
      </button>
    )}
  </div>
);

/* ------------------------------------------------------------------ */
/* Admin: paper + student modals                                       */
/* ------------------------------------------------------------------ */

const PaperFormModal = ({ initial, onSubmit, onClose }) => {
  const [title, setTitle] = useState(initial?.title || "");
  const [subject, setSubject] = useState(initial?.subject || "");
  const [year, setYear] = useState(initial?.year || YEARS[0]);
  const [semester, setSemester] = useState(initial?.semester || SEMESTERS[0]);
  const [branch, setBranch] = useState(initial?.branch || BRANCHES[0]);
  const [description, setDescription] = useState(initial?.description || "");
  const [file, setFile] = useState(null);
  const [fileError, setFileError] = useState("");

  const handleFile = (e) => {
    const f = e.target.files[0];
    setFileError("");
    if (!f) return;
    if (f.type !== "application/pdf") { setFileError("Please choose a PDF file."); return; }
    if (f.size > 4 * 1024 * 1024) { setFileError("Demo storage limit is 4MB — choose a smaller PDF, or leave empty."); return; }
    const reader = new FileReader();
    reader.onload = () => setFile({ name: f.name, dataUrl: reader.result });
    reader.readAsDataURL(f);
  };

  return (
    <Modal title={initial ? "Edit paper" : "Publish a new paper"} onClose={onClose} wide>
      <form
        className="ev-form"
        onSubmit={(e) => {
          e.preventDefault();
          onSubmit({ title, subject, year, semester, branch, description }, file);
        }}
      >
        <Field label="Paper title"><input className="ev-input" value={title} onChange={(e) => setTitle(e.target.value)} required /></Field>
        <div className="ev-form-row">
          <Field label="Subject"><input className="ev-input" value={subject} onChange={(e) => setSubject(e.target.value)} required /></Field>
          <Field label="Branch">
            <select className="ev-input" value={branch} onChange={(e) => setBranch(e.target.value)}>
              {BRANCHES.map((b) => <option key={b} value={b}>{b}</option>)}
            </select>
          </Field>
        </div>
        <div className="ev-form-row">
          <Field label="Semester">
            <select className="ev-input" value={semester} onChange={(e) => setSemester(e.target.value)}>
              {SEMESTERS.map((s) => <option key={s} value={s}>Semester {s}</option>)}
            </select>
          </Field>
          <Field label="Year">
            <select className="ev-input" value={year} onChange={(e) => setYear(e.target.value)}>
              {YEARS.map((y) => <option key={y} value={y}>{y}</option>)}
            </select>
          </Field>
        </div>
        <Field label="Description (optional)">
          <textarea className="ev-input ev-textarea" rows={3} value={description} onChange={(e) => setDescription(e.target.value)} />
        </Field>
        <Field label="PDF file (optional for this demo, max 4MB)" icon={<Upload size={14} />}>
          <input className="ev-input" type="file" accept="application/pdf" onChange={handleFile} />
        </Field>
        {fileError && <p className="ev-form-error">{fileError}</p>}
        {file && <p className="ev-form-hint"><Check size={13} /> {file.name} ready to attach</p>}
        <button className="ev-btn ev-btn-primary ev-btn-block" type="submit">{initial ? "Save changes" : "Publish paper"}</button>
      </form>
    </Modal>
  );
};

const AddStudentModal = ({ onSubmit, onClose }) => {
  const [name, setName] = useState("");
  const [enrollmentId, setEnrollmentId] = useState("");
  const [email, setEmail] = useState("");
  const [branch, setBranch] = useState(BRANCHES[0]);
  const [semester, setSemester] = useState(SEMESTERS[0]);
  const [password, setPassword] = useState("");

  return (
    <Modal title="Add a student account" onClose={onClose}>
      <form className="ev-form" onSubmit={(e) => { e.preventDefault(); onSubmit({ name, enrollmentId, email, branch, semester, password }); }}>
        <Field label="Full name"><input className="ev-input" value={name} onChange={(e) => setName(e.target.value)} required /></Field>
        <div className="ev-form-row">
          <Field label="Enrollment ID"><input className="ev-input" value={enrollmentId} onChange={(e) => setEnrollmentId(e.target.value)} required /></Field>
          <Field label="College email"><input className="ev-input" type="email" value={email} onChange={(e) => setEmail(e.target.value)} required /></Field>
        </div>
        <div className="ev-form-row">
          <Field label="Branch">
            <select className="ev-input" value={branch} onChange={(e) => setBranch(e.target.value)}>
              {BRANCHES.map((b) => <option key={b} value={b}>{b}</option>)}
            </select>
          </Field>
          <Field label="Semester">
            <select className="ev-input" value={semester} onChange={(e) => setSemester(e.target.value)}>
              {SEMESTERS.map((s) => <option key={s} value={s}>Semester {s}</option>)}
            </select>
          </Field>
        </div>
        <Field label="Temporary password"><input className="ev-input" value={password} onChange={(e) => setPassword(e.target.value)} required /></Field>
        <button className="ev-btn ev-btn-primary ev-btn-block" type="submit">Add student</button>
      </form>
    </Modal>
  );
};

/* ------------------------------------------------------------------ */
/* Student app                                                         */
/* ------------------------------------------------------------------ */

const StudentApp = ({ currentUser, papers, comments, bookmarks, downloadsHistory, onToggleBookmark, onDownload, onAddComment, onLogout, allStudents }) => {
  const [tab, setTab] = useState("browse");
  const [filters, setFilters] = useState({ q: "", subject: "", branch: "", semester: "", year: "" });
  const [expandedId, setExpandedId] = useState(null);

  const paperList = useMemo(() => Object.values(papers).sort((a, b) => new Date(b.uploadedAt) - new Date(a.uploadedAt)), [papers]);
  const subjects = useMemo(() => [...new Set(paperList.map((p) => p.subject))].sort(), [paperList]);
  const branches = useMemo(() => [...new Set(paperList.map((p) => p.branch))].sort(), [paperList]);

  const filtered = useMemo(() => paperList.filter((p) => {
    if (filters.q && !(`${p.title} ${p.subject}`.toLowerCase().includes(filters.q.toLowerCase()))) return false;
    if (filters.subject && p.subject !== filters.subject) return false;
    if (filters.branch && p.branch !== filters.branch) return false;
    if (filters.semester && p.semester !== filters.semester) return false;
    if (filters.year && p.year !== filters.year) return false;
    return true;
  }), [paperList, filters]);

  const myBookmarkIds = bookmarks[currentUser.id] || [];
  const myHistory = downloadsHistory[currentUser.id] || [];

  const renderGrid = (list) => (
    list.length === 0
      ? <EmptyState icon={<FileText size={28} />} title="No papers found" body="Try adjusting your filters or search terms." />
      : <div className="ev-grid">
          {list.map((p) => (
            <PaperCard
              key={p.id}
              paper={p}
              role="student"
              isBookmarked={myBookmarkIds.includes(p.id)}
              onToggleBookmark={onToggleBookmark}
              onDownload={onDownload}
              commentList={comments[p.id] || []}
              onAddComment={onAddComment}
              currentUser={currentUser}
              expanded={expandedId === p.id}
              onToggleExpand={(id) => setExpandedId((cur) => (cur === id ? null : id))}
            />
          ))}
        </div>
  );

  return (
    <div className="ev-app">
      <header className="ev-topbar">
        <div className="ev-topbar-brand"><Logo size={32} /><span>ExamVault</span></div>
        <div className="ev-topbar-tabs">
          <button className={tab === "browse" ? "active" : ""} onClick={() => setTab("browse")}><LayoutGrid size={14} /> Browse</button>
          <button className={tab === "bookmarks" ? "active" : ""} onClick={() => setTab("bookmarks")}><Bookmark size={14} /> Bookmarks</button>
          <button className={tab === "history" ? "active" : ""} onClick={() => setTab("history")}><Clock size={14} /> History</button>
          <button className={tab === "leaderboard" ? "active" : ""} onClick={() => setTab("leaderboard")}><Trophy size={14} /> Leaderboard</button>
        </div>
        <div className="ev-topbar-user">
          <div className="ev-user-chip">
            <div className="ev-user-avatar">{currentUser.name.split(" ").map((p) => p[0]).join("").slice(0, 2)}</div>
            <div>
              <strong>{currentUser.name}</strong>
              <span>{currentUser.points || 0} pts • {currentUser.branch}</span>
            </div>
          </div>
          <button className="ev-icon-btn" onClick={onLogout} title="Log out"><LogOut size={16} /></button>
        </div>
      </header>

      <main className="ev-main">
        {tab === "browse" && (
          <>
            <FilterBar filters={filters} setFilters={setFilters} subjects={subjects} branches={branches} />
            {renderGrid(filtered)}
          </>
        )}

        {tab === "bookmarks" && renderGrid(paperList.filter((p) => myBookmarkIds.includes(p.id)))}

        {tab === "history" && (
          myHistory.length === 0
            ? <EmptyState icon={<Clock size={28} />} title="No downloads yet" body="Papers you download will show up here with a timestamp." />
            : <div className="ev-card">
                <h3><Clock size={16} /> Download history</h3>
                <div className="ev-history-list">
                  {myHistory.map((h, i) => {
                    const p = papers[h.paperId];
                    if (!p) return null;
                    return (
                      <div key={i} className="ev-history-row">
                        <div><strong>{p.title}</strong><span>{p.subject} • {p.branch} • Sem {p.semester}</span></div>
                        <span className="ev-history-date">{formatDate(h.ts)}</span>
                      </div>
                    );
                  })}
                </div>
              </div>
        )}

        {tab === "leaderboard" && <LeaderboardView students={allStudents} currentUserId={currentUser.id} />}
      </main>
    </div>
  );
};

/* ------------------------------------------------------------------ */
/* Admin app                                                           */
/* ------------------------------------------------------------------ */

const AdminApp = ({ currentUser, papers, students, comments, onLogout, onAddPaper, onUpdatePaper, onDeletePaper, onAddStudent, onDeleteStudent, onReset }) => {
  const [tab, setTab] = useState("overview");
  const [paperModal, setPaperModal] = useState(null); // null | 'new' | paperObj
  const [studentModal, setStudentModal] = useState(false);

  const paperList = useMemo(() => Object.values(papers).sort((a, b) => new Date(b.uploadedAt) - new Date(a.uploadedAt)), [papers]);
  const totalDownloads = paperList.reduce((sum, p) => sum + (p.downloads || 0), 0);
  const totalComments = Object.values(comments).reduce((sum, list) => sum + list.length, 0);

  return (
    <div className="ev-app">
      <header className="ev-topbar ev-topbar-admin">
        <div className="ev-topbar-brand"><Logo size={32} /><span>ExamVault <em>Admin</em></span></div>
        <div className="ev-topbar-tabs">
          <button className={tab === "overview" ? "active" : ""} onClick={() => setTab("overview")}><BarChart3 size={14} /> Overview</button>
          <button className={tab === "papers" ? "active" : ""} onClick={() => setTab("papers")}><FileText size={14} /> Papers</button>
          <button className={tab === "students" ? "active" : ""} onClick={() => setTab("students")}><Users size={14} /> Students</button>
        </div>
        <div className="ev-topbar-user">
          <div className="ev-user-chip">
            <div className="ev-user-avatar ev-user-avatar-admin"><ShieldCheck size={16} /></div>
            <div><strong>{currentUser.name}</strong><span>Administrator</span></div>
          </div>
          <button className="ev-icon-btn" onClick={onLogout} title="Log out"><LogOut size={16} /></button>
        </div>
      </header>

      <main className="ev-main">
        {tab === "overview" && (
          <>
            <div className="ev-stat-grid">
              <div className="ev-stat-card"><FileText size={18} /><div><strong>{paperList.length}</strong><span>Papers in archive</span></div></div>
              <div className="ev-stat-card"><Users size={18} /><div><strong>{students.length}</strong><span>Registered students</span></div></div>
              <div className="ev-stat-card"><Download size={18} /><div><strong>{totalDownloads}</strong><span>Total downloads</span></div></div>
              <div className="ev-stat-card"><MessageCircle size={18} /><div><strong>{totalComments}</strong><span>Discussion comments</span></div></div>
            </div>
            <div className="ev-card">
              <h3><Sparkles size={16} /> Quick actions</h3>
              <div className="ev-quick-actions">
                <button className="ev-btn ev-btn-primary" onClick={() => setPaperModal("new")}><Plus size={15} /> Publish a paper</button>
                <button className="ev-btn ev-btn-ghost" onClick={() => setStudentModal(true)}><Plus size={15} /> Add a student</button>
                <button className="ev-btn ev-btn-ghost" onClick={onReset}><RotateCcw size={15} /> Reset demo data</button>
              </div>
            </div>
          </>
        )}

        {tab === "papers" && (
          <>
            <div className="ev-section-head">
              <h3>Manage papers</h3>
              <button className="ev-btn ev-btn-primary ev-btn-sm" onClick={() => setPaperModal("new")}><Plus size={14} /> Publish paper</button>
            </div>
            {paperList.length === 0
              ? <EmptyState icon={<FileText size={28} />} title="No papers yet" body="Publish the first paper to start the archive." />
              : <div className="ev-grid">
                  {paperList.map((p) => (
                    <PaperCard
                      key={p.id}
                      paper={p}
                      role="admin"
                      commentList={comments[p.id] || []}
                      adminActions={{ onEdit: (paper) => setPaperModal(paper), onDelete: onDeletePaper }}
                    />
                  ))}
                </div>}
          </>
        )}

        {tab === "students" && (
          <>
            <div className="ev-section-head">
              <h3>Manage students</h3>
              <button className="ev-btn ev-btn-primary ev-btn-sm" onClick={() => setStudentModal(true)}><Plus size={14} /> Add student</button>
            </div>
            {students.length === 0
              ? <EmptyState icon={<Users size={28} />} title="No students yet" body="Add a student account to get started." />
              : <div className="ev-card">
                  <table className="ev-table">
                    <thead><tr><th>Name</th><th>Enrollment ID</th><th>Email</th><th>Branch</th><th>Sem</th><th>Points</th><th></th></tr></thead>
                    <tbody>
                      {students.map((s) => (
                        <tr key={s.id}>
                          <td>{s.name}</td>
                          <td><code>{s.enrollmentId}</code></td>
                          <td>{s.email}</td>
                          <td>{s.branch}</td>
                          <td>{s.semester}</td>
                          <td>{s.points || 0}</td>
                          <td><button className="ev-icon-btn ev-icon-btn-danger" onClick={() => onDeleteStudent(s.id)}><Trash2 size={15} /></button></td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>}
          </>
        )}
      </main>

      {paperModal && (
        <PaperFormModal
          initial={paperModal === "new" ? null : paperModal}
          onClose={() => setPaperModal(null)}
          onSubmit={(form, file) => {
            if (paperModal === "new") onAddPaper(form, file);
            else onUpdatePaper(paperModal.id, form);
            setPaperModal(null);
          }}
        />
      )}
      {studentModal && (
        <AddStudentModal onClose={() => setStudentModal(false)} onSubmit={(form) => { onAddStudent(form); setStudentModal(false); }} />
      )}
    </div>
  );
};

/* ------------------------------------------------------------------ */
/* Root App                                                            */
/* ------------------------------------------------------------------ */

export default function App() {
  const [loading, setLoading] = useState(true);
  const [users, setUsers] = useState({});
  const [papers, setPapers] = useState({});
  const [bookmarks, setBookmarks] = useState({});
  const [downloads, setDownloads] = useState({});
  const [comments, setComments] = useState({});

  const [session, setSession] = useState(null);
  const [screen, setScreen] = useState("landing");
  const [authMode, setAuthMode] = useState("login");
  const [toasts, setToasts] = useState([]);

  const showToast = (msg, type = "info") => {
    const id = uid();
    setToasts((t) => [...t, { id, msg, type }]);
    setTimeout(() => setToasts((t) => t.filter((x) => x.id !== id)), 3200);
  };

  useEffect(() => {
    let cancelled = false;
    (async () => {
      const seed = buildSeed();
      const getOrInit = async (key, fallback) => {
        try {
          const res = await window.storage.get(key, true);
          if (res && res.value) return JSON.parse(res.value);
        } catch (e) { /* not found, fall through */ }
        try { await window.storage.set(key, JSON.stringify(fallback), true); } catch (e) { /* ignore */ }
        return fallback;
      };
      const [u, p, b, d, c] = await Promise.all([
        getOrInit("users-db", seed.users),
        getOrInit("papers-db", seed.papers),
        getOrInit("bookmarks-db", seed.bookmarks),
        getOrInit("downloads-db", seed.downloads),
        getOrInit("comments-db", seed.comments)
      ]);
      if (cancelled) return;
      setUsers(u); setPapers(p); setBookmarks(b); setDownloads(d); setComments(c);
      setLoading(false);
    })();
    return () => { cancelled = true; };
  }, []);

  const persist = async (key, value, setter) => {
    setter(value);
    try { await window.storage.set(key, JSON.stringify(value), true); }
    catch (e) { showToast("Could not sync that change — kept locally for now", "error"); }
  };

  const currentUser = session ? users[session.id] : null;

  /* ---------- auth ---------- */
  const studentLogin = (identifier, password) => {
    const id = Object.keys(users).find((k) => {
      const u = users[k];
      const idf = identifier.trim().toLowerCase();
      return u.role === "student" && (u.enrollmentId?.toLowerCase() === idf || u.email?.toLowerCase() === idf) && u.password === password;
    });
    if (id) {
      setSession({ id, role: "student" });
      setScreen("app");
      showToast(`Welcome back, ${users[id].name.split(" ")[0]}!`, "success");
    } else {
      showToast("Invalid credentials — check your enrollment ID/email and password.", "error");
    }
  };

  const adminLogin = (id, password) => {
    const u = users[id];
    if (u && u.role === "admin" && u.password === password) {
      setSession({ id, role: "admin" });
      setScreen("app");
      showToast("Welcome back, Administrator.", "success");
    } else {
      showToast("Invalid administrator ID or password.", "error");
    }
  };

  const registerStudent = (form) => {
    if (form.password !== form.confirm) { showToast("Passwords don't match.", "error"); return; }
    if (form.password.length < 4) { showToast("Password must be at least 4 characters.", "error"); return; }
    const exists = Object.values(users).some((u) => u.role === "student" &&
      (u.enrollmentId?.toLowerCase() === form.enrollmentId.toLowerCase() || u.email?.toLowerCase() === form.email.toLowerCase()));
    if (exists) { showToast("An account with this enrollment ID or email already exists.", "error"); return; }
    const id = uid();
    const newUser = { id, role: "student", name: form.name, enrollmentId: form.enrollmentId, email: form.email, branch: form.branch, semester: form.semester, password: form.password, points: 0, joinedAt: new Date().toISOString() };
    const next = { ...users, [id]: newUser };
    persist("users-db", next, setUsers);
    setSession({ id, role: "student" });
    setScreen("app");
    showToast("Account created — welcome to ExamVault!", "success");
  };

  const adjustPoints = (userId, delta) => {
    setUsers((prev) => {
      const u = prev[userId];
      if (!u) return prev;
      const next = { ...prev, [userId]: { ...u, points: Math.max(0, (u.points || 0) + delta) } };
      window.storage.set("users-db", JSON.stringify(next), true).catch(() => {});
      return next;
    });
  };

  const logout = () => { setSession(null); setScreen("landing"); setAuthMode("login"); };

  /* ---------- papers ---------- */
  const addPaper = (form, file) => {
    const id = uid();
    const paper = { id, ...form, fileName: file?.name || null, hasFile: !!file, downloads: 0, uploadedBy: currentUser.id, uploadedAt: new Date().toISOString() };
    const next = { ...papers, [id]: paper };
    persist("papers-db", next, setPapers);
    if (file) window.storage.set(`file:${id}`, file.dataUrl, true).catch(() => {});
    showToast("Paper published to the archive.", "success");
  };

  const updatePaper = (id, form) => {
    const next = { ...papers, [id]: { ...papers[id], ...form } };
    persist("papers-db", next, setPapers);
    showToast("Paper updated.", "success");
  };

  const deletePaper = (id) => {
    const next = { ...papers };
    delete next[id];
    persist("papers-db", next, setPapers);
    window.storage.delete(`file:${id}`, true).catch(() => {});
    showToast("Paper removed from the archive.", "success");
  };

  /* ---------- students (admin) ---------- */
  const addStudentManual = (form) => {
    const exists = Object.values(users).some((u) => u.role === "student" &&
      (u.enrollmentId?.toLowerCase() === form.enrollmentId.toLowerCase() || u.email?.toLowerCase() === form.email.toLowerCase()));
    if (exists) { showToast("A student with this enrollment ID or email already exists.", "error"); return; }
    const id = uid();
    const newUser = { id, role: "student", name: form.name, enrollmentId: form.enrollmentId, email: form.email, branch: form.branch, semester: form.semester, password: form.password, points: 0, joinedAt: new Date().toISOString() };
    persist("users-db", { ...users, [id]: newUser }, setUsers);
    showToast("Student account added.", "success");
  };

  const deleteStudent = (id) => {
    const next = { ...users };
    delete next[id];
    persist("users-db", next, setUsers);
    showToast("Student account removed.", "success");
  };

  /* ---------- bookmarks / downloads / comments ---------- */
  const toggleBookmark = (paperId) => {
    if (!currentUser) return;
    const mine = bookmarks[currentUser.id] || [];
    const has = mine.includes(paperId);
    const nextMine = has ? mine.filter((x) => x !== paperId) : [...mine, paperId];
    persist("bookmarks-db", { ...bookmarks, [currentUser.id]: nextMine }, setBookmarks);
    adjustPoints(currentUser.id, has ? -1 : 1);
    showToast(has ? "Removed from bookmarks." : "Saved to bookmarks.", "success");
  };

  const handleDownload = async (paper) => {
    let url = null, blob = null;
    if (paper.hasFile) {
      try {
        const res = await window.storage.get(`file:${paper.id}`, true);
        if (res?.value) url = res.value;
      } catch (e) { /* fall back below */ }
    }
    if (!url) {
      blob = generatePlaceholderPdf(paper.title, `${paper.subject} • Semester ${paper.semester} • ${paper.branch} • ${paper.year}`);
      url = URL.createObjectURL(blob);
    }
    const a = document.createElement("a");
    a.href = url;
    a.download = paper.fileName || `${paper.title.replace(/\s+/g, "_")}.pdf`;
    document.body.appendChild(a);
    a.click();
    a.remove();
    if (blob) setTimeout(() => URL.revokeObjectURL(url), 4000);

    const nextPapers = { ...papers, [paper.id]: { ...papers[paper.id], downloads: (papers[paper.id].downloads || 0) + 1 } };
    persist("papers-db", nextPapers, setPapers);

    if (currentUser?.role === "student") {
      const mine = downloads[currentUser.id] || [];
      const nextMine = [{ paperId: paper.id, ts: new Date().toISOString() }, ...mine].slice(0, 200);
      persist("downloads-db", { ...downloads, [currentUser.id]: nextMine }, setDownloads);
      adjustPoints(currentUser.id, 2);
    }
    showToast("Download started.", "success");
  };

  const addComment = (paperId, text) => {
    if (!currentUser || !text.trim()) return;
    const c = { id: uid(), studentId: currentUser.id, name: currentUser.name, text: text.trim(), ts: new Date().toISOString() };
    const mine = comments[paperId] || [];
    persist("comments-db", { ...comments, [paperId]: [...mine, c] }, setComments);
    adjustPoints(currentUser.id, 1);
  };

  const resetDemoData = () => {
    const seed = buildSeed();
    persist("users-db", seed.users, setUsers);
    persist("papers-db", seed.papers, setPapers);
    persist("bookmarks-db", seed.bookmarks, setBookmarks);
    persist("downloads-db", seed.downloads, setDownloads);
    persist("comments-db", seed.comments, setComments);
    showToast("Demo data reset.", "success");
  };

  const allStudents = useMemo(() => Object.values(users).filter((u) => u.role === "student"), [users]);

  /* ---------- render ---------- */

  return (
    <div className="ev-root">
      <style>{CSS}</style>
      <Toasts toasts={toasts} />

      {loading ? (
        <div className="ev-loading"><Loader2 className="ev-spin" size={28} /><span>Loading the archive…</span></div>
      ) : screen === "landing" ? (
        <Landing onPickStudent={() => { setScreen("studentAuth"); setAuthMode("login"); }} onPickAdmin={() => setScreen("adminAuth")} />
      ) : screen === "studentAuth" ? (
        <StudentAuth mode={authMode} setMode={setAuthMode} onLogin={studentLogin} onRegister={registerStudent} onBack={() => setScreen("landing")} />
      ) : screen === "adminAuth" ? (
        <AdminAuth onLogin={adminLogin} onBack={() => setScreen("landing")} />
      ) : screen === "app" && currentUser?.role === "student" ? (
        <StudentApp
          currentUser={currentUser}
          papers={papers}
          comments={comments}
          bookmarks={bookmarks}
          downloadsHistory={downloads}
          onToggleBookmark={toggleBookmark}
          onDownload={handleDownload}
          onAddComment={addComment}
          onLogout={logout}
          allStudents={allStudents}
        />
      ) : screen === "app" && currentUser?.role === "admin" ? (
        <AdminApp
          currentUser={currentUser}
          papers={papers}
          students={allStudents}
          comments={comments}
          onLogout={logout}
          onAddPaper={addPaper}
          onUpdatePaper={updatePaper}
          onDeletePaper={deletePaper}
          onAddStudent={addStudentManual}
          onDeleteStudent={deleteStudent}
          onReset={resetDemoData}
        />
      ) : (
        <Landing onPickStudent={() => setScreen("studentAuth")} onPickAdmin={() => setScreen("adminAuth")} />
      )}
    </div>
  );
}

/* ------------------------------------------------------------------ */
/* Styles                                                               */
/* ------------------------------------------------------------------ */

const CSS = `
@import url('https://fonts.googleapis.com/css2?family=Cinzel:wght@500;700&family=Plus+Jakarta+Sans:wght@400;500;600;700;800&family=IBM+Plex+Mono:wght@500;600&display=swap');

.ev-root {
  --ink: #0F1E36;
  --ink-light: #1A3156;
  --paper-bg: #F5F7FA;
  --card: #FFFFFF;
  --amber: #D4AF37;
  --amber-dark: #B8901C;
  --teal: #1E6B65;
  --coral: #9E2A2B;
  --line: #E2E8F0;
  --muted: #64748B;
  --text: #1E293B;
  font-family: 'Plus Jakarta Sans', system-ui, sans-serif;
  color: var(--text);
  background: var(--paper-bg);
  min-height: 100vh;
  width: 100%;
}
.ev-root * { box-sizing: border-box; }
.ev-root h1, .ev-root h2 { font-family: 'Cinzel', serif; font-weight: 700; margin: 0; letter-spacing: -0.5px; }
.ev-root h3 { font-family: 'Plus Jakarta Sans', sans-serif; font-weight: 700; margin: 0; }
.ev-root code { font-family: 'IBM Plex Mono', monospace; background: #E2E8F0; padding: 2px 6px; border-radius: 4px; font-size: 0.85em; color: var(--ink); }

.ev-loading { min-height: 100vh; display:flex; flex-direction:column; align-items:center; justify-content:center; gap:10px; color: var(--muted); }
.ev-spin { animation: ev-spin 1s linear infinite; }
@keyframes ev-spin { to { transform: rotate(360deg); } }

.ev-seal { border: 1.5px solid currentColor; border-radius: 6px; display:flex; align-items:center; justify-content:center; flex-shrink:0; background: rgba(255,255,255,0.8); font-weight:800; }
.ev-seal span { font-family:'IBM Plex Mono', monospace; font-size: 11px; }
.ev-tone-amber { color: var(--amber-dark); border-color: var(--amber); }
.ev-tone-coral { color: var(--coral); border-color: var(--coral); }

.ev-logo { display:flex; align-items:center; justify-content:center; }
.ev-logo-ring { width:100%; height:100%; border-radius: 12px; background: linear-gradient(135deg, var(--ink), var(--ink-light)); color: var(--amber); display:flex; align-items:center; justify-content:center; border: 2px solid var(--amber); box-shadow: 0 4px 12px rgba(15,30,54,0.15); }

.ev-toast-wrap { position: fixed; bottom: 18px; right: 18px; display:flex; flex-direction:column; gap:8px; z-index: 1000; }
.ev-toast { display:flex; align-items:center; gap:8px; background: var(--ink); color:#fff; padding: 10px 14px; border-radius: 10px; font-size: 13px; box-shadow: 0 8px 24px rgba(22,33,62,0.25); animation: ev-toast-in .2s ease; }
.ev-toast-error { background: var(--coral); }
.ev-toast-success { background: var(--teal); }
@keyframes ev-toast-in { from { opacity:0; transform: translateY(8px);} to { opacity:1; transform:none; } }

.ev-btn { font-family: inherit; border:none; cursor:pointer; display:inline-flex; align-items:center; gap:8px; padding: 12px 20px; border-radius: 8px; font-weight:600; font-size: 14px; transition: all 0.15s ease; }
.ev-btn:active { transform: scale(0.98); }
.ev-btn-block { width:100%; justify-content:center; }
.ev-btn-sm { padding: 8px 14px; font-size: 13px; border-radius: 6px; }
.ev-btn-primary { background: var(--ink); color: #fff; border: 1px solid var(--ink); }
.ev-btn-primary:hover { background: var(--ink-light); border-color: var(--ink-light); transform: translateY(-1px); }
.ev-btn-coral { background: var(--coral); color: #fff; }
.ev-btn-coral:hover { opacity:0.95; transform: translateY(-1px); }
.ev-btn-ghost { background: #fff; color: var(--ink); border: 1px solid var(--line); }
.ev-btn-ghost:hover { border-color: var(--ink); background: #FAF9F6; }
.ev-btn-ghost.ev-bookmarked { background: #FFF4DF; border-color: var(--amber); color: var(--amber-dark); }
.ev-btn-danger-ghost { background:#fff; color: var(--coral); border: 1.5px solid #F3CFCB; }
.ev-btn-danger-ghost:hover { background: #FDEEEC; }

.ev-icon-btn { border:none; background: #fff; border:1.5px solid var(--line); width:34px; height:34px; border-radius:9px; display:flex; align-items:center; justify-content:center; cursor:pointer; color: var(--ink); }
.ev-icon-btn:hover { border-color: var(--amber); }
.ev-icon-btn-primary { background: var(--ink); border-color: var(--ink); color:#fff; }
.ev-icon-btn-danger:hover { border-color: var(--coral); color: var(--coral); }

.ev-input { font-family: inherit; width:100%; padding: 11px 14px; border-radius: 8px; border: 1px solid var(--line); background:#fff; font-size: 14px; color: var(--text); outline:none; transition: border 0.15s ease; }
.ev-input:focus { border-color: var(--ink); box-shadow: 0 0 0 3px rgba(15,30,54,0.05); }
.ev-textarea { resize: vertical; }
.ev-pw-wrap { position:relative; }
.ev-pw-toggle { position:absolute; right:8px; top:50%; transform:translateY(-50%); background:none; border:none; cursor:pointer; color: var(--muted); }

.ev-landing { min-height:100vh; display:flex; align-items:center; justify-content:center; padding: 40px 24px; background: radial-gradient(circle at top right, rgba(212,175,55,0.05), transparent), var(--paper-bg); }
.ev-landing-inner { max-width: 800px; width:100%; text-align: center; }
.ev-brandmark { display:flex; flex-direction: column; align-items:center; gap:16px; margin-bottom: 24px; }
.ev-eyebrow { text-transform:uppercase; letter-spacing: 2px; font-size: 12px; color: var(--amber-dark); font-weight:800; }
.ev-landing h1 { font-size: 42px; color: var(--ink); margin-top: 4px; }
.ev-separator { width: 60px; height: 3px; background: var(--amber); margin: 16px auto 0; border-radius: 2px; }
.ev-landing-sub { color: var(--muted); font-size: 16px; max-width: 600px; line-height:1.6; margin: 16px auto 36px; }

.ev-landing-cards { display:flex; flex-direction: column; gap: 16px; max-width: 640px; margin: 0 auto; }
.ev-portal-card { display:flex; align-items:center; justify-content:space-between; width: 100%; text-align:left; background:#fff; border: 1px solid var(--line); border-radius:12px; padding: 20px 24px; cursor:pointer; transition: all .2s ease; box-shadow: 0 2px 4px rgba(0,0,0,0.02); }
.ev-portal-card-left { display: flex; align-items: center; gap: 18px; }
.ev-portal-card h3 { font-size: 17px; color: var(--ink); margin: 0 0 4px; }
.ev-portal-card p { font-size: 13.5px; color: var(--muted); margin:0; line-height:1.45; }
.ev-portal-arrow { transform: rotate(180deg); color: var(--muted); transition: all 0.2s ease; flex-shrink: 0; }
.ev-portal-card:hover { border-color: var(--amber); box-shadow: 0 8px 20px rgba(15,30,54,0.06); transform: translateY(-2px); }
.ev-portal-card:hover .ev-portal-arrow { color: var(--ink); transform: rotate(180deg) translateX(4px); }

.ev-landing-foot { margin-top: 40px; font-size: 13px; color: var(--muted); display: flex; flex-direction: column; align-items: center; gap: 8px; border-top: 1px solid var(--line); padding-top: 24px; }
.ev-landing-foot span { font-weight: 600; color: var(--ink); }

.ev-auth { min-height:100vh; display:grid; grid-template-columns: 450px 1fr; }
.ev-auth-brand { display:flex; flex-direction:column; justify-content:space-between; padding: 40px; color:#fff; position: relative; overflow: hidden; }
.ev-tone-bg-amber { background: linear-gradient(135deg, #0A1424, var(--ink)); border-right: 3px solid var(--amber); }
.ev-tone-bg-coral { background: linear-gradient(135deg, #1C0A0A, var(--coral)); border-right: 3px solid var(--amber); }
.ev-back-link { background:rgba(255,255,255,0.08); border:1px solid rgba(255,255,255,0.15); border-radius: 6px; color:#fff; display:flex; align-items:center; gap:8px; cursor:pointer; font-size: 13px; font-weight:600; padding: 8px 14px; width: fit-content; transition: all 0.15s ease; }
.ev-back-link:hover { background: rgba(255,255,255,0.15); }
.ev-auth-brand-mid { margin: auto 0; }
.ev-auth-brand-mid h2 { font-size: 28px; margin: 24px 0 12px; color: #fff; font-family: 'Cinzel', serif; line-height: 1.2; }
.ev-auth-line { width: 40px; height: 2px; background: var(--amber); margin-bottom: 20px; }
.ev-auth-brand-mid p { color: #94A3B8; font-size: 14.5px; max-width: 340px; line-height:1.6; }
.ev-auth-brand-foot { font-size: 12px; color: #64748B; font-family: 'IBM Plex Mono', monospace; }

.ev-auth-form-side { display:flex; flex-direction:column; justify-content:center; padding: 60px 40px; background: #fff; }
.ev-auth-form-container { max-width: 420px; width:100%; margin: 0 auto; }

.ev-auth-tabs { display:flex; gap:4px; background:#F1F5F9; border-radius:8px; padding:4px; margin-bottom:28px; }
.ev-auth-tabs button { flex:1; border:none; background:none; padding:10px; border-radius:6px; font-weight:600; font-size:14px; cursor:pointer; color: var(--muted); transition: all 0.15s ease; }
.ev-auth-tabs button.active { background:#fff; color: var(--ink); box-shadow: 0 2px 4px rgba(0,0,0,0.05); }
.ev-form { display:flex; flex-direction:column; gap:18px; }
.ev-form-row { display:grid; grid-template-columns: 1fr 1fr; gap:14px; }
.ev-field { display:flex; flex-direction:column; gap:6px; }
.ev-field-label { font-size: 12px; font-weight:700; color: var(--ink); text-transform: uppercase; letter-spacing: 0.5px; display:flex; align-items:center; gap:6px; }
.ev-form-error { color: var(--coral); font-size:12.5px; margin:-6px 0 0; }
.ev-form-hint { color: var(--teal); font-size:12.5px; margin:-6px 0 0; display:flex; align-items:center; gap:5px; }

.ev-app { min-height:100vh; display:flex; flex-direction:column; }
.ev-topbar { display:flex; align-items:center; gap:18px; background: var(--ink); padding: 14px 32px; position:sticky; top:0; z-index: 50; border-bottom: 2px solid var(--amber); }
.ev-topbar-admin { background: var(--ink); border-color: var(--ink); }
.ev-topbar-brand { display:flex; align-items:center; gap:10px; font-weight:800; font-size:16px; color: #fff; }
.ev-topbar-brand span { color: #fff; font-family: 'Cinzel', serif; letter-spacing: 0.5px; }
.ev-topbar-brand em { font-style:normal; color: var(--amber); font-weight:700; margin-left:4px; }
.ev-topbar-tabs { display:flex; gap:4px; margin: 0 auto; }
.ev-topbar-tabs button { display:flex; align-items:center; gap:6px; border:none; background:none; padding: 8px 13px; border-radius:9px; font-weight:600; font-size:13px; cursor:pointer; color: #94A3B8; }
.ev-topbar-tabs button.active { background: rgba(212,175,55,0.15); color: var(--amber); }
.ev-topbar-admin .ev-topbar-tabs button { color: #C9D0E0; }
.ev-topbar-admin .ev-topbar-tabs button.active { background: rgba(242,169,59,0.18); color: var(--amber); }
.ev-topbar-user { display:flex; align-items:center; gap:10px; }
.ev-user-chip { display:flex; align-items:center; gap:8px; }
.ev-user-avatar { width:34px; height:34px; border-radius:50%; background: var(--amber); color:#3A2700; font-weight:700; font-size:12px; display:flex; align-items:center; justify-content:center; }
.ev-user-avatar-admin { background: var(--coral); color:#fff; }
.ev-user-chip strong { display:block; font-size:13px; line-height:1.2; color: #fff; }
.ev-user-chip span { display:block; font-size:11px; color: #94A3B8; }
.ev-topbar-admin .ev-user-chip span { color: #A9B2C8; }
.ev-topbar-admin .ev-user-chip strong { color:#fff; }
.ev-topbar-admin .ev-icon-btn { background: rgba(255,255,255,0.06); border-color: rgba(255,255,255,0.15); color:#fff; }

.ev-main { flex:1; padding: 22px 24px 60px; max-width: 1180px; width:100%; margin: 0 auto; }

.ev-filterbar { display:flex; gap:10px; flex-wrap:wrap; margin-bottom:18px; }
.ev-search-box { display:flex; align-items:center; gap:8px; background:#fff; border:1.5px solid var(--line); border-radius:10px; padding: 0 12px; flex: 1 1 220px; color: var(--muted); }
.ev-search-box input { border:none; outline:none; padding: 10px 0; font-size:13.5px; width:100%; font-family:inherit; }
.ev-filter-select { width:auto; flex: 0 0 auto; min-width: 130px; }

.ev-grid { display:grid; grid-template-columns: repeat(auto-fill, minmax(290px, 1fr)); gap: 16px; }
.ev-paper-card { background: var(--card); border: 1px solid var(--line); border-radius: 16px; padding: 16px; position: relative; overflow: hidden; }
.ev-paper-card-top { display:flex; justify-content:space-between; align-items:flex-start; gap:10px; }
.ev-paper-tags { display:flex; gap:6px; flex-wrap:wrap; }
.ev-tag { font-size: 10.5px; font-weight:700; padding: 3px 8px; border-radius:999px; background:#EEF1F6; color: var(--muted); }
.ev-tag-subject { background:#FFF4DF; color: var(--amber-dark); }
.ev-paper-title { font-size: 15.5px; margin: 10px 0 4px; color: var(--ink); }
.ev-paper-desc { font-size: 12.5px; color: var(--muted); line-height:1.5; margin:0 0 8px; }
.ev-paper-meta-row { display:flex; gap:14px; font-size: 11px; color: var(--muted); }
.ev-paper-meta-row span { display:flex; align-items:center; gap:4px; }
.ev-perf { position:relative; border-top: 2px dashed var(--line); margin-top: 14px; padding-top: 14px; }
.ev-perf::before, .ev-perf::after { content:''; position:absolute; top:-8px; width:16px; height:16px; border-radius:50%; background: var(--paper-bg); border: 2px dashed var(--line); }
.ev-perf::before { left:-16px; }
.ev-perf::after { right:-16px; }
.ev-paper-actions { display:flex; align-items:center; gap:8px; flex-wrap:wrap; }
.ev-paper-filename { font-size: 11px; color: var(--muted); margin-left:auto; }

.ev-comments { margin-top: 14px; border-top: 1px solid var(--line); padding-top: 12px; display:flex; flex-direction:column; gap:10px; }
.ev-comments-empty { font-size:12.5px; color: var(--muted); margin:0; }
.ev-comment { display:flex; gap:9px; }
.ev-comment-avatar { width:28px; height:28px; border-radius:50%; background:var(--ink); color:#fff; font-size:10.5px; font-weight:700; display:flex; align-items:center; justify-content:center; flex-shrink:0; }
.ev-comment-meta { display:flex; gap:8px; align-items:baseline; font-size:12px; }
.ev-comment-meta span { color: var(--muted); font-size:11px; }
.ev-comment p { margin: 2px 0 0; font-size:12.5px; line-height:1.5; }
.ev-comment-form { display:flex; gap:8px; margin-top:4px; }

.ev-card { background:#fff; border:1px solid var(--line); border-radius:16px; padding:18px; margin-bottom:18px; }
.ev-card h3 { display:flex; align-items:center; gap:8px; font-size:15px; color: var(--ink); margin-bottom:14px; font-family:'Plus Jakarta Sans'; font-weight:700; }
.ev-stat-grid { display:grid; grid-template-columns: repeat(auto-fit, minmax(180px,1fr)); gap:14px; margin-bottom:18px; }
.ev-stat-card { background:#fff; border:1px solid var(--line); border-radius:14px; padding:16px; display:flex; align-items:center; gap:12px; color: var(--amber-dark); }
.ev-stat-card div strong { display:block; font-size:20px; color: var(--ink); }
.ev-stat-card div span { font-size:11.5px; color: var(--muted); }
.ev-quick-actions { display:flex; gap:10px; flex-wrap:wrap; }
.ev-section-head { display:flex; justify-content:space-between; align-items:center; margin-bottom:16px; }
.ev-section-head h3 { font-size:18px; color: var(--ink); }
.ev-table { width:100%; border-collapse: collapse; font-size:13px; }
.ev-table th { text-align:left; font-size:11px; text-transform:uppercase; letter-spacing:0.5px; color: var(--muted); padding: 8px 10px; border-bottom: 1.5px solid var(--line); }
.ev-table td { padding: 10px; border-bottom: 1px solid var(--line); }

.ev-history-list { display:flex; flex-direction:column; gap:2px; }
.ev-history-row { display:flex; justify-content:space-between; align-items:center; padding: 10px 0; border-bottom: 1px solid var(--line); }
.ev-history-row strong { display:block; font-size:13.5px; }
.ev-history-row span { font-size:11.5px; color: var(--muted); }
.ev-history-date { font-size:12px; color: var(--muted); }

.ev-leaderboard { display:grid; grid-template-columns: 1.1fr 1fr; gap: 16px; align-items:start; }
.ev-rank-list { display:flex; flex-direction:column; gap:4px; }
.ev-rank-row { display:flex; align-items:center; gap:12px; padding: 10px 8px; border-radius:10px; }
.ev-rank-me { background: #FFF4DF; }
.ev-rank-pos { width:26px; text-align:center; font-weight:700; color: var(--muted); font-family:'IBM Plex Mono'; }
.ev-rank-name { flex:1; }
.ev-rank-name strong { display:block; font-size:13.5px; }
.ev-rank-name span { font-size:11.5px; color: var(--muted); }
.ev-rank-points { font-weight:700; font-family:'IBM Plex Mono'; color: var(--ink); font-size:13px; }

.ev-modal-overlay { position:fixed; inset:0; background: rgba(22,33,62,0.45); display:flex; align-items:center; justify-content:center; z-index: 200; padding: 16px; }
.ev-modal { background:#fff; border-radius: 16px; width: 100%; max-width: 480px; box-shadow: 0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04); overflow: hidden; animation: ev-modal-zoom 0.2s cubic-bezier(0.16, 1, 0.3, 1); }
.ev-modal-wide { max-width: 640px; }
.ev-modal-head { display: flex; align-items: center; justify-content: space-between; padding: 16px 20px; border-bottom: 1px solid var(--line); background: var(--paper-bg); }
.ev-modal-head h3 { font-size: 16px; color: var(--ink); }
.ev-modal-body { padding: 20px; }
@keyframes ev-modal-zoom { from { opacity: 0; transform: scale(0.95); } to { opacity: 1; transform: scale(1); } }

/* Empty States & Utility classes */
.ev-empty { text-align: center; padding: 40px 20px; color: var(--muted); display: flex; flex-direction: column; align-items: center; gap: 8px; width: 100%; }
.ev-empty h4 { margin: 8px 0 0; color: var(--ink); font-size: 15px; }
.ev-empty p { margin: 0; font-size: 13px; max-width: 280px; line-height: 1.5; }

/* Responsive adjustments */
@media (max-width: 868px) {
  .ev-auth { grid-template-columns: 1fr; min-height: auto; }
  .ev-auth-brand { min-height: 280px; padding: 32px; border-right: none; border-bottom: 3px solid var(--amber); }
  .ev-auth-form-side { padding: 40px 20px; }
  .ev-leaderboard { grid-template-columns: 1fr; }
  .ev-topbar { padding: 14px 16px; flex-wrap: wrap; justify-content: space-between; }
  .ev-topbar-tabs { order: 3; width: 100%; justify-content: center; margin-top: 8px; }
}

@media (max-width: 480px) {
  .ev-form-row { grid-template-columns: 1fr; gap: 18px; }
  .ev-landing h1 { font-size: 32px; }
  .ev-portal-card { padding: 16px; }
  .ev-portal-card-left { gap: 12px; }
}
`;